### ISSUE TITLE
Ignore Chrome's "playing audio" string. 

### ISSUE THREAD

**Issue by yahoo1999** [erengy/anisthesia#3]
While having Taiga recognize me watching on Crunchyroll I encountered one issue. Google Chrome started putting "- playing audio" string to page title everytime page plays audio. The problem is that if there's quite long silence the string goes away from page title and Taiga redetects it as new episode being watched. When silence comes to end, Chrome puts "playing audio" in the page title again and I am getting notified about watching new episode again. 

It's not as annoying as it was before as with v1.3 taiga doesn't play sound with the notification anymore, but action center get's kinda spammed. 

Detected episode with "playing audio" string in Polish: 
![2018-04-09 10_21_30-crunchyroll - watch karakai jozu no takagi-san episode 12 - letter _ first day o](https://user-images.githubusercontent.com/18481896/38487346-197473b2-3be0-11e8-8077-76dd4c01d802.png)

**Comment by erengy** [comment]
Taiga does ignore the "Audio playing" string, but ignoring all localized strings (e.g. "odtwarzanie dźwięku", "Ses çalıyor", "オーディオ再生中です") is not a feasible solution: Chrome is available in 50+ languages, and translations can change over time.

Chrome appends the audio state to tab accessibility labels, but not to the regular window title. I'll try making use of that, hopefully without breaking something else.

P.S. As a temporary solution, you can try adding ` - odtwarzanie dźwięku` to Taiga's *Settings → Advanced → Recognition / Ignored strings*.

**Comment by yahoo1999** [comment]
Sure, thank you. One more thing kinda annoys me. It look's like Taiga is looking for active tab instead of open one, so if I switch to e.g. Messenger to see if someone texted me after getting back to crunchyroll page it get's redetected because it was lost after switching tabs. It's not major issue but I feel it would be more convinient to detect just open, not active tabs. If it's possible of course.

**Comment by erengy** [comment]
Taiga does the exact thing you suggest. When you switch to another tab, it checks the other ones to see if previously detected media is still there.

The problem you have might also be related to using the browser in a non-English language. And unlike the window title, there's no workaround for the tabs.
