### ISSUE TITLE
Media Player Classic Qute Theater recognition stopped working

### ISSUE THREAD

**Issue by mfsoup** [erengy/anisthesia#6]
Not sure what changed, but Taiga stopped working with the latest mpc-qt compiled on Windows. The old version of mpc-qt works with the same Taiga installation. Tested with Taiga v1.4.0-beta.2.

The new repository for mpc-qt is https://github.com/cmdrkotori/mpc-qt-origin. The link in #1 is outdated.

**Comment by erengy** [comment]
Is there a recent build that I can download?

**Comment by mfsoup** [comment]
> 
> 
> Is there a recent build that I can download?

Yes, a new build was just posted in the linked repo yesterday. I just tried the new build and it doesn't seem to be working with Taiga still.

**Comment by erengy** [comment]
I couldn't run that build, unfortunately. For some reason, it just closes immediately at startup without visible errors.

My best guess is that it's built with a newer version of Qt and the class name that is used to detect the application window has changed. Could you help me test that?

First, please download [WinSpy++](https://www.catch22.net/software/winspy) and drag its finder over mpc-qt's window to read the class name. It should be something like `Qt5QWindowIcon` or `Qt5151QWindowIcon`. In that case, the following should work:

1. Download [players.anisthesia](https://raw.githubusercontent.com/erengy/anisthesia/master/data/players.anisthesia) and copy it to `Taiga\data\players.anisthesia`.
2. Open the file with a text editor and find the `Media Player Classic Qute Theater` section.
3. Replace `Qt5QWindowIcon` with `^Qt.+QWindowIcon` and save the file.
4. Restart Taiga.

**Comment by mfsoup** [comment]
Thanks, replacing `Qt5QWindowIcon` with `Qt5151QWindowIcon` found in WinSpy++ made it start working again.

Edit: not sure if this should be closed or not since you might be updating it on the repo.
